export PATH="$HOME/bin:$HOME/.yarn/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export HELIOS_TESTING_PROFILE=local
export ALTERNATE_EDITOR=""
export EDITOR=emacsclient
export GOPATH="$HOME"
export CARGO_TARGET_DIR="$HOME/.cache/cargo/target"
export GITHUB_TOKEN="$(cat ~/secrets/ghe-token)"
export GITHUB_ENTERPRISE_TOKEN="$(cat ~/secrets/ghe-token)"
export WASI_SYSROOT=/opt/wasi-sdk/wasi-sysroot
